services:
  rasa:
    image: rasa/rasa:3.6.20-full
    command: run --enable-api --cors "*"
    ports:
      - "5005:5005"
    volumes:
      - ./data:/app/data
      - ./actions:/app/actions
      - ./config.yml:/app/config.yml
      - ./domain.yml:/app/domain.yml
      - ./credentials.yml:/app/credentials.yml
      - ./endpoints.yml:/app/endpoints.yml
      - ./models:/app/models
    depends_on:
      - actions

  actions:
    image: rasa/rasa-sdk:3.6.2
    command: rasa run actions
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
